# Generated by Django 4.2.7 on 2023-12-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valor',
            old_name='name',
            new_name='idarte',
        ),
        migrations.RemoveField(
            model_name='valor',
            name='description',
        ),
        migrations.AddField(
            model_name='valor',
            name='valor',
            field=models.FloatField(default=0, max_length=100, verbose_name='Valores'),
            preserve_default=False,
        ),
    ]
