# Generated by Django 4.2.7 on 2023-12-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='description',
        ),
        migrations.AddField(
            model_name='artista',
            name='idade',
            field=models.TextField(default='', max_length=2, verbose_name='Idade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artista',
            name='nascionalidade',
            field=models.TextField(default='', max_length=50, verbose_name='Nascionalidade'),
            preserve_default=False,
        ),
    ]
