# Generated by Django 4.2.7 on 2023-12-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arte',
            name='url',
            field=models.CharField(default='', max_length=50, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
