# Generated by Django 4.2.7 on 2023-12-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='description',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.TextField(default='', max_length=11, verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
